-- Legacy migration: older schema used booking_details and flat columns.
-- Current app uses booking_data (JSON), selected_menu (JSON), category, created_at — see schema.sql.
-- If upgrading an old DB, prefer backing up data then applying schema.sql / Hibernate ddl-auto=update on a fresh schema.
